spring:
  application:
    name: springboot-sns
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:mem:snsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: null
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
logging:
  level:
    io.lettuce.core: INFO
    org.springframework.data.redis: INFO
    org.springframework.session: INFO
